name: Publish (pfnet)
on:
  push:
    branches:
      - pfn-main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dylanvann/publish-github-action@973d5c2eec5df00513bb013e4424eaf04117ebd1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
